title: "Albert Raphael Assimagbe"
logo: "/images/profession_photo_Raphael.jpeg?raw=true"
description: >
  Data analyst and economist focused on using Python, SQL, and econometrics tools 
  to solve sustainability challenges and drive strategic decisions. 
  I excel at communicating complex information clearly and effectively.

  [![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-blue?style=flat&logo=linkedin)](https://www.linkedin.com/in/assimagbe/)
  [![GitHub](https://img.shields.io/badge/GitHub-Repo-black?style=flat&logo=github)](https://github.com/albert-raphael)
  [![Email](https://img.shields.io/badge/Email-Contact-red?style=flat&logo=gmail)](mailto:albertraphael96@email.com)

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

# google_analytics: UA-000000-0





















#title: Albert Raphael Assimagbe # your name (or website title) here
#logo: "/images/profession  photo Raphael.jpeg?raw=true" # your photo (or logo) here 
#description: > # your text below (remove <br> if you don't need line break)
 <br>
Data analyst and economist focused on using Python, SQL, and econometrics tools to solve sustainability challenges and drive strategic decisions. 
I excel at communicating complex information clearly and effectively.
 <br>
 
 #<a href="https://www.linkedin.com/in/assimagbe/">View My LinkedIn Profile</a> 

 <br><br>

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
