title: Albert Raphael Assimagbe # your name (or website title) here

logo: "/images/profession  photo Raphael.jpeg?raw=true" # your photo (or logo) here 

description: > # your text below (remove <br> if you don't need line break)

 <br>
Economist and data analyst with expertise in environmental and resource economics, data-driven policy evaluation, and business development. Skilled in Python, SQL, and econometrics tools to derive actionable insights and support strategic decision-making. Passionate about using data to address sustainability challenges and drive innovation..
 <br>
 
 <a href="https://www.linkedin.com/in/assimagbe/">View My LinkedIn Profile</a> 

 <br><br>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
